### ISSUE TITLE
libfive backend?

### ISSUE THREAD

**Issue by lf94** [curv3d/curv#163]
After some thinking it may be beneficial to try and use libfive as a backend instead of Curv having its own. This would consolidate work across the code-CAD space and continue to allow us to use the Curv language. I believe Curv's strength is its language and growing library of utilities and examples (similar to OpenSCAD's strength). libfive's way of rendering is unique and most likely the future of this kind of modeling. It scales much better than anything before it. Essentially implementing an optimizing virtual machine in a shader (optimizing calculations per-pixel), I can't imagine anything else being better.

**Comment by doug-moen** [comment]
Curv already has a libfive back end, if you use `-Omgen=sharp` as an option when generating a mesh file.
In 2021 we spent over a month testing it as an alternative to the default, and in the end, there were too many cases where it generates bad rendering artifacts. I don't recommend using it.

The Curv libfive backend may produce worse results when using libfive studio on the same signed distance functions, for the subset of cases where libfive will even accept the SDF. But Curv and libfive are mismatched, because many of the SDFs in the curv standard library and examples directory will not be accepted by libfive studio, because native libfive will not allow you to use loops or conditional expressions when defining an SDF. The mechanism I use to interface Curv to libfive was the one recommended to me by Matt Keeter, and works with any SDF (even the ones excluded by libfive studio), but it doesn't work very well for a lot of inputs. Simple stuff like cubes and spheres are rendered extremely well. When you go outside of that, such as a human skull model one of my collaborators made, or a CAD model by the same person, or anything interesting and artistic, then you don't want to use it. The set of SDFs that you need to avoid is just too limiting.

A different way of interfacing Curv to libfive, one that errors out when an SDF forbidden by libfive is used, would produce better results, avoiding rendering errors where you currently get them, but it would be a lot of work to create, and is probably not worth the effort, due to the limitations.

**Comment by lf94** [comment]
I forgot we had it! I'll have to experiment further then with the backend. I believe there's still a large set of models that are useful within libfive's constraints...

**Comment by doug-moen** [comment]
All of my current meshing algorithms work by sampling the distance field at a fixed interval, filling in a voxel array with the values, then feeding the values into a mesher.

What I want instead is an adaptive meshing algorithm that is given the signed distance function as an argument. It will detect that the current location is in a region of high curvature, and it will take more samples at a higher resolution. This will reduce the tendency to round off sharp edges and corners in a CAD type model. Native libfive is adaptive, but it places strong requirements on the underlying SDF. An adaptive algorithm without the libfive restrictions could be a significant improvement over the current algorithm while still supporting a wide range of SDFs.

Matt Keeter has suggested that I should compute gradients using automatic differentiation, and use the gradients to improve the mesh, which is one of the things libfive does. It may be worth trying (you don't know until you try). It seems likely to fail badly for SDFs that use conditionals and loops. My gut instinct is that I should improve mesh quality by other means (those which can more easily be shown to be robust), despite the strong consensus that you should use gradients for sharp edge detection. Sharp edge detection is fragile and when it fails you get bad artifacts that you can't do anything about, so there needs to be an alternative algorithm that you can fall back to that doesn't work this way.

It seems that to get this, someone needs to write a mesher that takes a signed distance function as an argument (like libfive in native mode), but which doesn't require accurate gradients in order to produce reasonable results (unlike libfive).

**Comment by lf94** [comment]
> I should compute gradients using automatic differentiation

I wish I could help but this is way beyond my current knowledge. 

> SDFs that use conditionals and loops

Does this rule out recursion and alternative ways to alternate values?

I would love to hear more about what requirements exactly libfive SDFs require.

**Comment by doug-moen** [comment]
Yes, this rules out recursion and alternate ways to return alternate values. I've confirmed that with Matt.

In the general case, libfive relies on computing the [gradient](https://en.wikipedia.org/wiki/Gradient) of the distance function during meshing. If the shape contains sharp corners or edges, then there is no gradient at the sharp edge, and the meshing algorithm fails and creates artifacts. Conditionals and loops will commonly create sharp corners and edges, so they are forbidden. The exception to this rule is that there is a special case for the union and intersection operators, which are implemented using `min` and `max`. The libfive meshing algorithm has special case code for `min` and `max` that allows it to handle sharp corners and edges when they are created using these functions. A corollary is that libfive needs to know the source code of the distance function, and only mathematical functions known to libfive will work, at least if you use libfive using Studio (the Curv integration works differently).

Warning: this account is partly based on guesswork, as I do not fully understand how Libfive works. If you use the libfive Oracle API, then different rules apply. Curv uses the Oracle API, but I don't have the deep mathematical background needed to use it *correctly* (if that is possible for Curv, which I'm a bit skeptical that it can be done). In theory, "using it correctly" would avoid rendering artifacts.

**Comment by doug-moen** [comment]
Fractals are a special case, because the interesting 3D fractal shapes created by the fractal community allow you to zoom in forever, and more interesting details are revealed the farther you zoom in. These shapes commonly do not have a gradient anywhere. Since they have infinitely complex surface detail, every point on the surface counts as a sharp edge. So in theory, I believe it is impossible for libfive to render these directly from an SDF. These fractals are defined using an IFS -- iterated function system -- meaning that loops are involved.

**Comment by lf94** [comment]
How is ntopology, a company using libfive, then creating interesting shapes? They're for sure using repetition in some form... Are they using techniques that maybe we should apply?

**Comment by doug-moen** [comment]
One way to avoid rendering and other problems with signed distance field is to restrict the user to a set of high level primitives that are hand picked and hand tuned to not cause problems. You don't give the user the ability to define arbitrary distance functions. If there is a small number of such primitives, you can spend extra implementation effort to eliminate problems with each primitive. For example, the video game Dreams uses SDF but restricts itself to a limited number of carefully designed high level primitives.

The libfive Oracle API works well for this approach. I don't know how to write an oracle that wraps an arbitrary distance function, but writing an oracle that is hand tuned for something as specialized as spatial repetition, if that's the example, should be feasible. The flip side of oracles is that they are considerably more difficult to write than distance functions. Ntopology can hire experts in multivariate calculus and linear algebra who can figure this stuff out. Note, I don't actually know what Ntopology is doing internally, so this is all just a hypothetical example.

**Comment by lf94** [comment]
That sounds good enough for me! I'd like to hear from @mkeeter what he knows about how ntopology uses libfive to generate interesting shapes. If we need a set of hand picked primitives I believe this is completely fine and can exist in its own file in lib/.
