### ISSUE TITLE
Any possibility to calculate the volume of the shape?

### ISSUE THREAD

**Issue by Xiaoyuew** [curv3d/curv#84]
I want to calculate the volume of a complicated shape without exporting it to mesh or something else, is it possible to do that within the .curv file?

**Comment by doug-moen** [comment]
AFAIK there's no practical way to do that in Curv at the present time. I mean, you could, because Curv is Turing complete, but I suspect it would be very slow, and I've not spent any time researching the problem or adding features to make it fast. What is your application or use case for computing a volume?
