### ISSUE TITLE
Build issues on Linux Mint 19.3 / Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Digital-Monk** [curv3d/curv#85]
Build problems:
1. CMake complained about OPENGL_gl_LIBRARY being NOTFOUND.  Able to fix this by editing Makefile and adding `-DOpenGL_GL_PREFERENCE=GLVND` to the cmake line in the `release` target.  The other option is `LEGACY`, and I don't know how much of this is dependent on CMake version (I've got 3.10.2) and how much is dependent on OS platform (Linux Mint 19.3, which is based on Ubuntu 18.04 LTS)
2. ld was unable to find `-lGL`.  Found on the web that apparently somehow libGL.so doesn't always get linked to libGL.so.1.  For me, the location was `/usr/lib/x86_64-linux-gnu`, and I needed to `sudo ln -sfn libGL.so.1 libGL.so`.  This is obviously not your problem, but perhaps some breadcrumbs in the install instructions for troubleshooting.

After those two things, I've got curv build and installed and running fine!

**Comment by doug-moen** [comment]
Interesting problem, since I do regular build testing on Ubuntu 18.04 LTS.

You shouldn't need to make any of these changes. In theory, you should just install the correct packages and it should work. I think you are missing a `*-dev` package related to the GPU hardware you are using.

On my system, the file `/usr/lib/x86_64-linux-gnu/libGL.so` is owned by the package `libglvnd-dev`, which is installed. But I didn't install this package explicitly, it was pulled in as a dependency by something else, probably by `libgl1-mesa-dev`.

**Comment by Digital-Monk** [comment]
Hmmm...  Must be something that Mint did on top of Ubuntu that isn't quite lining up.  Mint's package policies, especially around video drivers, are different from Ubuntu's, so that seems reasonable.

`libgl1-mesa-dev` and `libglvnd-dev` are both installed on my system, so not sure.  Not your problem, regardless :)   Just wanted to leave some breadcrumbs in case they helped anybody else.

Very impressed by curv so far.  Love live editing, and love that previews are instantaneous!

**Comment by Digital-Monk** [comment]
No idea what happened on my first machine.  Build this on a second machine, also running Mint 19.3, and it just worked.
