### ISSUE TITLE
Documentation problem? 1..51 by 100 gives [1, 101]

### ISSUE THREAD

**Issue by isaacdnew** [curv3d/curv#96]
**The bug**
There's a problem with either the documentation or the ``i .. j by k`` list-constructor. The documentation (at curv/docs/language/lists.rst) says this:

> ``i .. j by k``
> Similar to ``i..j``, except that the step value is ``k`` instead of ``1``.
> The step value may be positive or negative, and need not be an integer.
> For example, ``1..0 by -0.25`` is ``[1, 0.75, 0.5, 0.25, 0]``.

As a new user of curv, I interpreted this to mean that ``1..51 by 100`` would evaluate to the list ``[1]``. However, when I tried it out in the interactive console, 101 was included.

It seems that ``i..j by k`` works like this (or similarly to this):
- Divide the size of the range (given by ``j - i``) by ``k``: in my example, ``(51 - 1) / 100 = 0.50``
- Round the result and add 1: ``0.50`` becomes ``1``, which becomes ``2``
- Include that many elements in the list, starting at ``i`` and stepping by ``k``: the result is the list ``[1, 101]``

One of two things should happen here:
- Update the documentation to reflect this behavior
- Change this behavior (and further clarify it in the documentation)

**To Reproduce**
1. In the curv interactive console, type ``1..51 by 100`` and hit ``Enter``.
2. Output is ``[1, 101]``

**Expected behavior**
Output is ``[1]``

**System Information:**
 - Operating System: Microsoft Windows 10 Pro
 - CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)
 - Amount of system memory: 48 GB
 - GPU manufacturer, model and version: Nvidia Quadro P520
 - GPU driver, if on Linux: N/A
 - As far as I know, I am not running the `curv` command using a remote viewing protocol like VNC or NX.
 - Not running the `curv` command inside a VM; using MINGW64 shell from MSYS2
 - Not using the Ubuntu Linux Snap package (not running Ubuntu).
 - Curv Version:
```
Curv: 0.4-634-g8e5d7dc3-dirty
Compiler: gcc 10.1.0
Windows
GPU: NVIDIA Corporation, Quadro P520/PCIe/SSE2
OpenGL: 4.6.0 NVIDIA 443.17
```

**Comment by doug-moen** [comment]
In `first .. last by step`, the number of elements in the list is:
```
let delta = round((last - first)/step) in
if (delta < 0) 0 else delta + 1
```
In `first ..< last by step`, the number of elements in the list is:
```
let delta = round((last - first)/step) in
if (delta < 0) 0 else delta
```

This code assumes that `(last-first)` is intended to be an integer multiple of `step`, and therefore that  `(last - first)/step` is intended to be an integer. Since all arithmetic is floating point, the result might not be an exact integer due to floating point inaccuracy, so we call `round` to convert the result to an integer.

A typical use case that this algorithm is designed to handle:
```
0 ..< tau by (tau/n)
```
where `n` is some positive integer. This divides a circle (`tau` radians) into `n` equal segments. Without the use of `round`, this code will occasionally deliver the wrong number of segments.

(Note that the C++ implementation calls the C++ `round` function, which rounds away from 0, whereas the Curv `round` function rounds to the nearest even. So the Curv code that I gave above differs from the current C++ implementation in certain edge cases.)

In your example, `1..51 by 100`, the value of `last-first` is `50`, which is not even close to an integer multiple of the step value (`100`). So you are using the operator in a way that it isn't designed for.

**Comment by doug-moen** [comment]
If I were to change the implementation of `x..y by z`, what would I change it to? What were you trying to accomplish in your code by using such oversize step values?

**Comment by isaacdnew** [comment]
I wasn't actually trying to accomplish anything by using an oversized step value. I was just experimenting in the interactive console to familiarize myself with the basics. My main concern is that the existing documentation doesn't mention the big assumption that ``first .. last by step`` makes—that ``(last-first)`` must be an integer multiple of ``step``. If someone like me wrongly assumes that they can be "sloppy" with this notation (e.g. they write something like my example for whatever reason), they could be quite confused. I think the behavior can (and should) remain the same, but I think the documentation should explicitly mention the integer-multiple requirement.

**Comment by doug-moen** [comment]
Okay, then, thanks for the report, and I will update the documentation to make the assumptions more clear.
